const BASE = import.meta.env?.BASE_URL ?? '/'
const assetPath = (path) => `${BASE}${path.replace(/^\/+/, '')}`

export const ASSETS = {
  backgrounds: {
    titleHarborMorning: { key: 'bg_title_harbor_morning', path: assetPath('fishing-game/assets/backgrounds/bg_title_harbor_morning.png'), status: 'ready' },
    homeBase: { key: 'bg_home_base', path: assetPath('fishing-game/assets/backgrounds/bg_home_base.png'), status: 'ready' },
    mapTown: { key: 'bg_map_town', path: assetPath('fishing-game/assets/backgrounds/bg_map_town.png'), status: 'ready' },
    townQuiet: { key: 'bg_town_quiet', path: assetPath('fishing-game/assets/backgrounds/bg_town_quiet.svg'), status: 'ready' },
    townGrowing: { key: 'bg_town_growing', path: assetPath('fishing-game/assets/backgrounds/bg_town_growing.svg'), status: 'ready' },
    townBustling: { key: 'bg_town_bustling', path: assetPath('fishing-game/assets/backgrounds/bg_town_bustling.svg'), status: 'ready' },
    fishingHarbor: { key: 'bg_fishing_harbor', path: assetPath('fishing-game/assets/backgrounds/bg_fishing_harbor_v2.svg'), status: 'ready' },
    fishingBay: { key: 'bg_fishing_bay', path: assetPath('fishing-game/assets/backgrounds/bg_fishing_bay_v2.svg'), status: 'ready' },
    fishingCape: { key: 'bg_fishing_cape', path: assetPath('fishing-game/assets/backgrounds/bg_fishing_cape_v2.svg'), status: 'ready' },
  },
  characters: {
    guideDefault: { key: 'ch_guide_default', path: assetPath('fishing-game/assets/characters/ch_guide_default.png'), status: 'ready' },
    playerDefault: { key: 'ch_player_default', path: assetPath('fishing-game/assets/characters/ch_player_default.png'), status: 'ready' },
    playerDefaultUi: { key: 'ch_player_default_ui', path: assetPath('fishing-game/assets/characters/ch_player_default_ui.png'), status: 'ready' },
    fishingHero: { key: 'ch_fishing_hero', path: assetPath('fishing-game/assets/generated/fishing_player_hero.webp'), status: 'ready' },
    fishmonger: { key: 'ch_npc_fishmonger', path: assetPath('fishing-game/assets/characters/ch_npc_fishmonger_v2.svg'), status: 'ready' },
    guideStaff: { key: 'ch_npc_guide_staff', path: assetPath('fishing-game/assets/characters/ch_npc_guide_staff_v2.svg'), status: 'ready' },
    youngFisher: { key: 'ch_npc_young_fisher', path: assetPath('fishing-game/assets/characters/ch_npc_young_fisher_v2.svg'), status: 'ready' },
    harborCaptain: { key: 'ch_npc_harbor_captain', path: assetPath('fishing-game/assets/characters/ch_npc_harbor_captain_v2.svg'), status: 'ready' },
    dinerOwner: { key: 'ch_npc_diner_owner', path: assetPath('fishing-game/assets/characters/ch_npc_diner_owner_v2.svg'), status: 'ready' },
  },
  facilities: {
    market: { key: 'town_facility_market', path: assetPath('fishing-game/assets/town/town_facility_market.svg'), status: 'ready' },
    pier: { key: 'town_facility_pier', path: assetPath('fishing-game/assets/town/town_facility_pier.svg'), status: 'ready' },
    guide: { key: 'town_facility_guide', path: assetPath('fishing-game/assets/town/town_facility_guide.svg'), status: 'ready' },
    festival: { key: 'town_facility_festival', path: assetPath('fishing-game/assets/town/town_facility_festival.svg'), status: 'ready' },
    fishShop: { key: 'town_facility_fish_shop', path: assetPath('fishing-game/assets/town/town_facility_fish_shop.svg'), status: 'ready' },
    diner: { key: 'town_facility_diner', path: assetPath('fishing-game/assets/town/town_facility_diner.svg'), status: 'ready' },
  },
  facilityLevels: {
    marketLv1: { key: 'town_facility_market_lv1', path: assetPath('fishing-game/assets/town/town_facility_market_lv1.svg'), status: 'ready' },
    marketLv3: { key: 'town_facility_market_lv3', path: assetPath('fishing-game/assets/town/town_facility_market_lv3.svg'), status: 'ready' },
    marketLv5: { key: 'town_facility_market_lv5', path: assetPath('fishing-game/assets/town/town_facility_market_lv5.svg'), status: 'ready' },
    pierLv1: { key: 'town_facility_pier_lv1', path: assetPath('fishing-game/assets/town/town_facility_pier_lv1.svg'), status: 'ready' },
    pierLv3: { key: 'town_facility_pier_lv3', path: assetPath('fishing-game/assets/town/town_facility_pier_lv3.svg'), status: 'ready' },
    pierLv5: { key: 'town_facility_pier_lv5', path: assetPath('fishing-game/assets/town/town_facility_pier_lv5.svg'), status: 'ready' },
    guideLv1: { key: 'town_facility_guide_lv1', path: assetPath('fishing-game/assets/town/town_facility_guide_lv1.svg'), status: 'ready' },
    guideLv3: { key: 'town_facility_guide_lv3', path: assetPath('fishing-game/assets/town/town_facility_guide_lv3.svg'), status: 'ready' },
    guideLv5: { key: 'town_facility_guide_lv5', path: assetPath('fishing-game/assets/town/town_facility_guide_lv5.svg'), status: 'ready' },
    festivalLv1: { key: 'town_facility_festival_lv1', path: assetPath('fishing-game/assets/town/town_facility_festival_lv1.svg'), status: 'ready' },
    festivalLv3: { key: 'town_facility_festival_lv3', path: assetPath('fishing-game/assets/town/town_facility_festival_lv3.svg'), status: 'ready' },
    festivalLv5: { key: 'town_facility_festival_lv5', path: assetPath('fishing-game/assets/town/town_facility_festival_lv5.svg'), status: 'ready' },
  },
  fish: {
    ajiIcon: { key: 'fish_aji_icon', path: assetPath('fishing-game/assets/fish/fish_aji_icon.svg'), status: 'ready' },
    madaiIcon: { key: 'fish_madai_icon', path: assetPath('fishing-game/assets/fish/fish_madai_icon.svg'), status: 'ready' },
    blackBassIcon: { key: 'fish_black_bass_icon', path: assetPath('fishing-game/assets/fish/fish_black_bass_icon.svg'), status: 'ready' },
    buriIcon: { key: 'fish_buri_icon', path: assetPath('fishing-game/assets/fish/fish_buri_icon.svg'), status: 'ready' },
    kueIcon: { key: 'fish_kue_icon', path: assetPath('fishing-game/assets/fish/fish_kue_icon.svg'), status: 'ready' },
    sabaIcon: { key: 'fish_saba_icon', path: assetPath('fishing-game/assets/fish/fish_saba_icon.svg'), status: 'ready' },
    isakiIcon: { key: 'fish_isaki_icon', path: assetPath('fishing-game/assets/fish/fish_isaki_icon.svg'), status: 'ready' },
    hirameIcon: { key: 'fish_hirame_icon', path: assetPath('fishing-game/assets/fish/fish_hirame_icon.svg'), status: 'ready' },
    kanpachiIcon: { key: 'fish_kanpachi_icon', path: assetPath('fishing-game/assets/fish/fish_kanpachi_icon.svg'), status: 'ready' },
  },
  fishingField: {
    waterBase: { key: 'ff_water_base_01', path: assetPath('fishing-game/assets/fishing-field/water/water_base_01.svg'), status: 'ready' },
    waterPattern: { key: 'ff_water_pattern_01', path: assetPath('fishing-game/assets/fishing-field/water/water_pattern_01.svg'), status: 'ready' },
    waterHighlight: { key: 'ff_water_highlight_01', path: assetPath('fishing-game/assets/fishing-field/water/water_highlight_01.svg'), status: 'ready' },
    underwaterDepth: { key: 'ff_underwater_depth_01', path: assetPath('fishing-game/assets/fishing-field/water/underwater_depth_01.svg'), status: 'ready' },
    fishShadowSmallIdle: { key: 'ff_fish_shadow_s_idle_01', path: assetPath('fishing-game/assets/fishing-field/fish_shadow/fish_shadow_s_idle_01.svg'), status: 'ready' },
    fishShadowMediumIdle: { key: 'ff_fish_shadow_m_idle_01', path: assetPath('fishing-game/assets/fishing-field/fish_shadow/fish_shadow_m_idle_01.svg'), status: 'ready' },
    fishShadowMediumTurn: { key: 'ff_fish_shadow_m_turn_01', path: assetPath('fishing-game/assets/fishing-field/fish_shadow/fish_shadow_m_turn_01.svg'), status: 'ready' },
    fishShadowLargeIdle: { key: 'ff_fish_shadow_l_idle_01', path: assetPath('fishing-game/assets/fishing-field/fish_shadow/fish_shadow_l_idle_01.svg'), status: 'ready' },
    rock01: { key: 'ff_rock_01', path: assetPath('fishing-game/assets/fishing-field/field_objects/rock_01.svg'), status: 'ready' },
    seaweed01: { key: 'ff_seaweed_01', path: assetPath('fishing-game/assets/fishing-field/field_objects/seaweed_01.svg'), status: 'ready' },
    lureIdle: { key: 'ff_lure_idle_01', path: assetPath('fishing-game/assets/fishing-field/lure/lure_idle_01.svg'), status: 'ready' },
    lurePull: { key: 'ff_lure_pull_01', path: assetPath('fishing-game/assets/fishing-field/lure/lure_pull_01.svg'), status: 'ready' },
    lureSplash: { key: 'ff_lure_splash_01', path: assetPath('fishing-game/assets/fishing-field/lure/lure_splash_01.svg'), status: 'ready' },
    lureTrail: { key: 'ff_lure_trail_01', path: assetPath('fishing-game/assets/fishing-field/lure/lure_trail_01.svg'), status: 'ready' },
    rippleSmall: { key: 'ff_ripple_small_01', path: assetPath('fishing-game/assets/fishing-field/fx/fx_ripple_small_01.svg'), status: 'ready' },
    followWave: { key: 'ff_follow_wave_01', path: assetPath('fishing-game/assets/fishing-field/fx/fx_follow_wave_01.svg'), status: 'ready' },
    rippleBite: { key: 'ff_ripple_bite_01', path: assetPath('fishing-game/assets/fishing-field/fx/fx_ripple_bite_01.svg'), status: 'ready' },
    hitFlash: { key: 'ff_hit_flash_01', path: assetPath('fishing-game/assets/fishing-field/fx/fx_hit_flash_01.svg'), status: 'ready' },
    retrieveButtonWait: { key: 'ff_retrieve_button_wait_01', path: assetPath('fishing-game/assets/fishing-field/ui/retrieve_button_wait_01.svg'), status: 'ready' },
    retrieveButtonShortReel: { key: 'ff_retrieve_button_short_reel_01', path: assetPath('fishing-game/assets/fishing-field/ui/retrieve_button_short_reel_01.svg'), status: 'ready' },
    retrieveButtonSlowReel: { key: 'ff_retrieve_button_slow_reel_01', path: assetPath('fishing-game/assets/fishing-field/ui/retrieve_button_slow_reel_01.svg'), status: 'ready' },
    locationHarbor: { key: 'ff_location_harbor', path: assetPath('fishing-game/assets/fishing-field/location/location_harbor_overlay.svg'), status: 'ready' },
    locationBay: { key: 'ff_location_bay', path: assetPath('fishing-game/assets/fishing-field/location/location_bay_overlay.svg'), status: 'ready' },
    locationCape: { key: 'ff_location_cape', path: assetPath('fishing-game/assets/fishing-field/location/location_cape_overlay.svg'), status: 'ready' },
  },
  bosses: {
    harborRunner: { key: 'boss_harbor_runner', path: assetPath('fishing-game/assets/boss/boss_harbor_runner.svg'), status: 'ready' },
    bayHunter: { key: 'boss_bay_hunter', path: assetPath('fishing-game/assets/boss/boss_bay_hunter.svg'), status: 'ready' },
    kue: { key: 'boss_kue', path: assetPath('fishing-game/assets/boss/boss_kue.svg'), status: 'ready' },
  },
  rewards: {
    sticker: { key: 'reward_sticker', path: assetPath('fishing-game/assets/rewards/reward_sticker.svg'), status: 'ready' },
    ticket: { key: 'reward_ticket', path: assetPath('fishing-game/assets/rewards/reward_ticket.svg'), status: 'ready' },
    icebox: { key: 'reward_icebox', path: assetPath('fishing-game/assets/rewards/reward_icebox.svg'), status: 'ready' },
  },
  equipment: {
    rodBasic: { key: 'equip_rod_basic', path: assetPath('fishing-game/assets/equipment/rod_basic.svg'), status: 'ready' },
    rodCarbon: { key: 'equip_rod_carbon', path: assetPath('fishing-game/assets/equipment/rod_carbon.svg'), status: 'ready' },
    rodPremium: { key: 'equip_rod_premium', path: assetPath('fishing-game/assets/equipment/rod_premium.svg'), status: 'ready' },
    baitWorm: { key: 'equip_bait_worm', path: assetPath('fishing-game/assets/equipment/bait_worm.svg'), status: 'ready' },
    baitShrimp: { key: 'equip_bait_shrimp', path: assetPath('fishing-game/assets/equipment/bait_shrimp.svg'), status: 'ready' },
    baitSpecial: { key: 'equip_bait_special', path: assetPath('fishing-game/assets/equipment/bait_special.svg'), status: 'ready' },
  },
  ui: {
    resultFrame: { key: 'ui_result_frame', path: assetPath('fishing-game/assets/ui/ui_result_frame.svg'), status: 'ready' },
    resultNewRecord: { key: 'ui_result_new_record', path: assetPath('fishing-game/assets/ui/result_new_record.webp'), status: 'ready' },
    panelHarbor: { key: 'ui_panel_harbor', path: assetPath('fishing-game/assets/ui/ui_panel_harbor.svg'), status: 'ready' },
    buttonPrimary: { key: 'ui_button_primary', path: assetPath('fishing-game/assets/ui/ui_button_primary.svg'), status: 'ready' },
    spotPinHarbor: { key: 'ui_spot_pin_harbor', path: assetPath('fishing-game/assets/ui/ui_spot_pin_harbor.svg'), status: 'ready' },
    spotPinBay: { key: 'ui_spot_pin_bay', path: assetPath('fishing-game/assets/ui/ui_spot_pin_bay.svg'), status: 'ready' },
    spotPinCape: { key: 'ui_spot_pin_cape', path: assetPath('fishing-game/assets/ui/ui_spot_pin_cape.svg'), status: 'ready' },
  },
}

export const flattenAssets = () => Object.values(ASSETS).flatMap(group => Object.values(group))
